[versions]
composekn = "0.5.65"
kotlin = "2.4.0"
compose-ui = "1.12.1"
compose-ui-published = "1.12.1-ckn.0.5.65"
compose-maven-deps = "1.11.1"
coroutines = "1.10.2"

[libraries]
composekn-bom = { module = "com.composekn:compose-kn-bom", version.ref = "composekn" }
composekn-linux = { module = "com.composekn:compose-kn-linux", version.ref = "composekn" }
composekn-windows = { module = "com.composekn:compose-kn-windows", version.ref = "composekn" }
composekn-resources = { module = "com.composekn:compose-kn-resources", version.ref = "composekn" }
composekn-skiko = { module = "com.composekn:skiko", version.ref = "composekn" }
composekn-compose-ui = { module = "com.composekn.compose:ui", version.ref = "compose-ui-published" }
composekn-compose-foundation = { module = "com.composekn.compose:foundation", version.ref = "compose-ui-published" }
composekn-compose-material3 = { module = "com.composekn.compose:material3", version.ref = "compose-ui-published" }

[plugins]
composekn-host = { id = "com.composekn.host", version.ref = "composekn" }
composekn-resources = { id = "com.composekn.resources", version.ref = "composekn" }
composekn-settings = { id = "com.composekn.settings", version.ref = "composekn" }
