#!/usr/bin/env bash
# 把 ComposeKN 用的 Skiko 发成 com.composekn:skiko:<composekn.version>。
#
# 必须在 nix-shell（shell.nix）内运行，保证 x86_64-w64-mingw32-g++ 在 PATH：
#   nix-shell ./shell.nix -I nixpkgs=$NIXPKGS_URL --run ./scripts/publish-skiko-composekn.sh
#
# 需要：pkg-config（linux）、SKIA_MINGW_PREBUILT、GITHUB_TOKEN
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CKN_VER="$(grep '^composekn.version=' "$REPO/gradle.properties" | cut -d= -f2)"
: "${GITHUB_TOKEN:?GITHUB_TOKEN required}"
: "${GITHUB_ACTOR:=github}"
OWNER="${GITHUB_REPOSITORY_OWNER:-TetraploidHuman}"
GH_REPO_NAME="${GITHUB_REPOSITORY##*/}"
GH_REPO_NAME="${GH_REPO_NAME:-ComposeKN}"

info() { printf '\033[36m==>\033[0m %s\n' "$1"; }
warn() { printf '\033[33m!!\033[0m %s\n' "$1"; }
die() { printf '\033[31m!!\033[0m %s\n' "$1" >&2; exit 1; }

PREBUILT="${SKIA_MINGW_PREBUILT:-}"
if [ -z "$PREBUILT" ] && [ -d /tmp/composekn-skia-mingw ]; then
  TAG="$(cat "$REPO/vendor/skiko/skia-mingw/SKIA_TAG" 2>/dev/null || true)"
  CAND="/tmp/composekn-skia-mingw/skia-mingw-${TAG}"
  [ -d "$CAND" ] && PREBUILT="$CAND"
fi
[ -n "$PREBUILT" ] && [ -f "$PREBUILT/libs/libskia.a" ] \
  || die "SKIA_MINGW_PREBUILT missing libskia.a (got: ${PREBUILT:-empty})"

command -v x86_64-w64-mingw32-g++ >/dev/null 2>&1 \
  || die "x86_64-w64-mingw32-g++ not in PATH — wrap with nix-shell ./shell.nix --run"
info "mingw CXX: $(command -v x86_64-w64-mingw32-g++)"

GEN_ICU="$REPO/vendor/skiko/skiko/src/windowsMain/cpp/win32/win32_icu_data.generated.cpp"
if [ ! -f "$GEN_ICU" ] && [ -f "$PREBUILT/icudtl.dat" ]; then
  ICUDTL_ABS="$(cd "$(dirname "$PREBUILT/icudtl.dat")" && pwd)/$(basename "$PREBUILT/icudtl.dat")"
  ICUDTL_ESC="${ICUDTL_ABS//\\/\\\\}"
  ICUDTL_ESC="${ICUDTL_ESC//\"/\\\"}"
  cat > "$GEN_ICU" <<EOF
/* auto-generated by publish-skiko-composekn.sh — do not commit */
extern "C" {
__asm__(
    ".section .rdata,\\"dr\\"\\n"
    ".p2align 12\\n"
    ".globl composekn_icudtl_data\\n"
    "composekn_icudtl_data:\\n"
    ".incbin \\"$ICUDTL_ESC\\"\\n"
    ".globl composekn_icudtl_end\\n"
    "composekn_icudtl_end:\\n"
    ".text\\n"
);
}
EOF
fi

info "Publishing com.composekn:skiko:$CKN_VER (linuxX64+mingwX64; skip *KotlinMetadata)"

# afterEvaluate 再盖 groupId：skiko 自己的 publishing.kt 会把 group 设回 org.jetbrains.skiko
INIT="$(mktemp)"
trap 'rm -f "$INIT"' EXIT
cat > "$INIT" <<EOF
gradle.projectsLoaded {
    rootProject.allprojects { p ->
        p.tasks.configureEach { t ->
            if (t.name.contains("KotlinMetadata")) {
                t.enabled = false
            }
        }
        p.pluginManager.withPlugin("maven-publish") {
            p.extensions.configure(org.gradle.api.publish.PublishingExtension) { pub ->
                pub.repositories.maven {
                    name = "GitHubPackages"
                    url = uri("https://maven.pkg.github.com/$OWNER/$GH_REPO_NAME")
                    credentials {
                        username = System.getenv("GITHUB_ACTOR") ?: "github"
                        password = System.getenv("GITHUB_TOKEN")
                    }
                }
                pub.repositories.maven {
                    name = "ComposeKnLocal"
                    url = uri(new File("$REPO/build/maven-repo"))
                }
            }
        }
        p.afterEvaluate {
            p.group = "com.composekn"
            p.version = "$CKN_VER"
            def publishing = p.extensions.findByType(org.gradle.api.publish.PublishingExtension)
            if (publishing != null) {
                publishing.publications.withType(org.gradle.api.publish.maven.MavenPublication).configureEach { mp ->
                    mp.groupId = "com.composekn"
                    mp.version = "$CKN_VER"
                }
            }
        }
    }
}
EOF

cd "$REPO/vendor/skiko/skiko"
./gradlew --init-script "$INIT" --no-daemon \
  -Pdeploy.version="$CKN_VER" \
  -Pskiko.skia.mingw.dir="$PREBUILT/libs" \
  publishLinuxX64PublicationToComposeKnLocalRepository \
  publishMingwX64PublicationToComposeKnLocalRepository \
  publishLinuxX64PublicationToGitHubPackagesRepository \
  publishMingwX64PublicationToGitHubPackagesRepository

info "Local maven-repo after skiko publish:"
find "$REPO/build/maven-repo" -type f \( -iname '*skiko*' -o -path '*/jetbrains/skiko/*' \) 2>/dev/null | sort | head -80 || true

[ -d "$REPO/build/maven-repo/com/composekn/skiko-linuxx64/$CKN_VER" ] \
  || die "missing com/composekn/skiko-linuxx64/$CKN_VER (groupId override failed?)"
[ -d "$REPO/build/maven-repo/com/composekn/skiko-mingwx64/$CKN_VER" ] \
  || die "missing com/composekn/skiko-mingwx64/$CKN_VER (groupId override failed?)"

info "Synthesize com.composekn:skiko root"
chmod +x "$REPO/scripts/synthesize-kmp-root-modules.sh"
"$REPO/scripts/synthesize-kmp-root-modules.sh" "$REPO/build/maven-repo"

ROOT="$REPO/build/maven-repo/com/composekn/skiko/$CKN_VER"
[ -f "$ROOT/skiko-$CKN_VER.module" ] \
  || die "no synthesized $ROOT/skiko-$CKN_VER.module"

info "Upload synthesized skiko root → GitHub Packages"
chmod +x "$REPO/scripts/upload-maven-artifacts-to-gh-packages.sh"
"$REPO/scripts/upload-maven-artifacts-to-gh-packages.sh" "$ROOT"
if [ -f "$REPO/build/maven-repo/com/composekn/skiko/maven-metadata.xml" ]; then
  "$REPO/scripts/upload-maven-artifacts-to-gh-packages.sh" \
    "$REPO/build/maven-repo/com/composekn/skiko/maven-metadata.xml"
fi

info "done"
find "$REPO/build/maven-repo/com/composekn" -iname '*skiko*' -name '*.klib' 2>/dev/null | sort || true
