#!/usr/bin/env bash
# 把 ComposeKN 用的 Skiko 发成 com.composekn:skiko:<composekn.version>。
#
# CI / 本机：
#   - linuxX64：需要 pkg-config（fontconfig/wayland/egl/…）
#   - mingwX64：需要 SKIA_MINGW_PREBUILT + nix-shell 里的 mingw 交叉编译器
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CKN_VER="$(grep '^composekn.version=' "$REPO/gradle.properties" | cut -d= -f2)"
: "${GITHUB_TOKEN:?GITHUB_TOKEN required}"
: "${GITHUB_ACTOR:=github}"
OWNER="${GITHUB_REPOSITORY_OWNER:-TetraploidHuman}"
GH_REPO_NAME="${GITHUB_REPOSITORY##*/}"
GH_REPO_NAME="${GH_REPO_NAME:-ComposeKN}"

info() { printf '\033[36m==>\033[0m %s\n' "$1"; }
warn() { printf '\033[33m!!\033[0m %s\n' "$1"; }

PREBUILT="${SKIA_MINGW_PREBUILT:-}"
if [ -z "$PREBUILT" ] && [ -d /tmp/composekn-skia-mingw ]; then
  TAG="$(cat "$REPO/vendor/skiko/skia-mingw/SKIA_TAG" 2>/dev/null || true)"
  CAND="/tmp/composekn-skia-mingw/skia-mingw-${TAG}"
  [ -d "$CAND" ] && PREBUILT="$CAND"
fi

MINGW_PROP=()
if [ -n "$PREBUILT" ] && [ -f "$PREBUILT/libs/libskia.a" ]; then
  MINGW_PROP=( -Pskiko.skia.mingw.dir="$PREBUILT/libs" )
  info "mingw Skia: ${MINGW_PROP[*]}"
  GEN_ICU="$REPO/vendor/skiko/skiko/src/windowsMain/cpp/win32/win32_icu_data.generated.cpp"
  if [ ! -f "$GEN_ICU" ] && [ -f "$PREBUILT/icudtl.dat" ]; then
    ICUDTL_ABS="$(cd "$(dirname "$PREBUILT/icudtl.dat")" && pwd)/$(basename "$PREBUILT/icudtl.dat")"
    ICUDTL_ESC="${ICUDTL_ABS//\\/\\\\}"
    ICUDTL_ESC="${ICUDTL_ESC//\"/\\\"}"
    cat > "$GEN_ICU" <<EOF
/* auto-generated by publish-skiko-composekn.sh — do not commit */
extern "C" {
__asm__(
    ".section .rdata,\\"dr\\"\\n"
    ".p2align 12\\n"
    ".globl composekn_icudtl_data\\n"
    "composekn_icudtl_data:\\n"
    ".incbin \\"$ICUDTL_ESC\\"\\n"
    ".globl composekn_icudtl_end\\n"
    "composekn_icudtl_end:\\n"
    ".text\\n"
);
}
EOF
  fi
else
  warn "no SKIA_MINGW_PREBUILT — mingwX64 skiko publish may fail"
fi

nix_run() {
  local args=( )
  if [ -n "${NIXPKGS_URL:-}" ]; then
    args+=( -I "nixpkgs=$NIXPKGS_URL" )
  fi
  if [ -f "$REPO/shell.nix" ] && command -v nix-shell >/dev/null 2>&1; then
    nix-shell "$REPO/shell.nix" "${args[@]}" --run "$1"
  else
    bash -lc "$1"
  fi
}

info "Publishing com.composekn:skiko:$CKN_VER"

INIT="$(mktemp)"
cat > "$INIT" <<EOF
gradle.projectsLoaded {
    rootProject.allprojects { p ->
        p.pluginManager.withPlugin("maven-publish") {
            p.extensions.configure(org.gradle.api.publish.PublishingExtension) { pub ->
                pub.publications.withType(org.gradle.api.publish.maven.MavenPublication).configureEach {
                    groupId = "com.composekn"
                    version = "$CKN_VER"
                }
                pub.repositories.maven {
                    name = "GitHubPackages"
                    url = uri("https://maven.pkg.github.com/$OWNER/$GH_REPO_NAME")
                    credentials {
                        username = System.getenv("GITHUB_ACTOR") ?: "github"
                        password = System.getenv("GITHUB_TOKEN")
                    }
                }
                pub.repositories.maven {
                    name = "ComposeKnLocal"
                    url = uri(new File("$REPO/build/maven-repo"))
                }
            }
        }
    }
}
EOF

cd "$REPO/vendor/skiko/skiko"
# mingw bridges 需要交叉编译器 → 整段放进 nix-shell（有 PREBUILT/mingw.dir 时）
GRADLE_CMD=(
  ./gradlew --init-script "$INIT"
  -Pdeploy.version="$CKN_VER"
  "${MINGW_PROP[@]}"
  publishKotlinMultiplatformPublicationToGitHubPackagesRepository
  publishLinuxX64PublicationToGitHubPackagesRepository
  publishMingwX64PublicationToGitHubPackagesRepository
  publishKotlinMultiplatformPublicationToComposeKnLocalRepository
  publishLinuxX64PublicationToComposeKnLocalRepository
  publishMingwX64PublicationToComposeKnLocalRepository
  --continue --no-daemon
)

if [ ${#MINGW_PROP[@]} -gt 0 ]; then
  nix_run "${GRADLE_CMD[*]}"
else
  "${GRADLE_CMD[@]}"
fi

rm -f "$INIT"
info "done (check $REPO/build/maven-repo/com/composekn/skiko*)"
